# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build iot-task`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t iot-task`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system iot-task && \
          adduser --system -G iot-task iot-task

COPY dist/iot-task iot-task
RUN chown -R iot-task:iot-task .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix iot-task --omit=dev -f install

CMD [ "node", "iot-task" ]
